const $ = id => document.getElementById(id);
const formats = { landscape:[1200,675], square:[1080,1080], portrait:[1080,1350] };
const GIPHY_API_KEY = "GlVGYHkr3WSBnllca54iNt0yFbjz7L65";
const FEATURED_ENDPOINT = "https://featured.mypoint.cards";

const solidColors = ["#ED213A","#3498db","#2ecc71","#f39c12","#9b59b6","#34495e","#1abc9c","#000000","#e74c3c","#f1c40f","#95a5a6","#ffffff","#e84393","#8B4513"];
const gradients = [["to right","#f12711","#f5af19"],["to right","#8e2de2","#4a00e0"],["to right","#00b09b","#96c93d"],["45deg","#ff9a9e","#fad0c4"],["to right","#4facfe","#00f2fe"],["135deg","#667eea","#764ba2"],["to right","#2c3e50","#4ca1af"],["to right","#f953c6","#b91d73"],["to right","#11998e","#38ef7d"],["45deg","#fc4a1a","#f7b733"],["to right","#43cea2","#185a9d"],["135deg","#ff0844","#ffb199"],["to right","#2b5876","#4e4376"],["to right","#6a3093","#a044ff"],["to right","#BF953F","#FCF6BA","#B38728","#FBF5B7","#AA771C"],["to right","#8e9eab","#eef2f3","#8e9eab"],["to right","#536976","#292E49","#536976"]];
const emojis = "😀 😂 😍 🥰 😎 🤔 😅 😢 😡 🤯 🤩 😴 😇 😬 🤗 🥳 🤡 😄 🙂 😉 😆 🥺 😤 👍 🙏 💪 🙌 👀 🤷‍♂️ 🤦‍♀️ 🧠 👑 🫶 👎 ✌️ 🤝 👏 🤷‍♀️ 🤦‍♂️ 🤜🤛 🧑‍💻 🧑‍🚀 🧑‍🎨 ❤️ 🎉 ✨ 🔥 💯 🚫 ❌ ⭐ 🌟 💙 💚 💜 🖤 🤍 💖 💡 💥 ☀️ 🌙 ✅ ⚡ 🚀 ▪️ ▫️ ⚫ ⚪ 🔴 🔵 🔸 🔹 ▶️ 🔽 💠 📈 📱 💻 ⚽ 🏀 🎮 🎵 🎬 📚 🎯 📝 📢 🎙️ 🇦🇺 🇧🇩 🇧🇷 🇨🇦 🇨🇳 🇪🇬 🇩🇪 🇮🇩 🇮🇱 🇵🇸 🇷🇺 🇸🇦 🇿🇦 🇪🇸 🇦🇪 🇫🇷 🇮🇳 🇮🇹 🇯🇵 🇲🇾 🇲🇽 🇳🇬 🇵🇭 🇸🇬 🇰🇷 🇹🇷 🇬🇧 🇺🇸 🇻🇳".split(" ");

let bg={type:"solid",color:"#ED213A",gradient:null,image:null,imageObj:null,scale:"contain",darkness:20,posX:50,posY:50};
let blocks=[], selectedId=null, nextId=1, dragState=null;

function setStatus(t,ok=true){$("status").textContent=t;$("status").style.color=ok?"#8fbc8f":"#ff8f8f";}
function makeBlock(text="New text"){return{id:nextId++,text,x:50,y:50,width:70,font:"Arial, sans-serif",size:54,color:"#ffffff",align:"center",lineHeight:1.2,bold:true,italic:false,shadow:true};}
function byId(id){return blocks.find(b=>b.id===id);}
function renderSwatches(){
  $("solidColors").innerHTML=solidColors.map((c,i)=>`<button class="swatch ${i===0?"active":""}" data-solid="${c}" style="background:${c}"></button>`).join("");
  $("gradients").innerHTML=gradients.map(g=>`<button class="swatch" data-gradient='${JSON.stringify(g)}' style="background:linear-gradient(${g.join(",")})"></button>`).join("");
  $("emojiGrid").innerHTML=emojis.map(e=>`<button class="emojiBtn" data-emoji="${e}">${e}</button>`).join("");
}
function stageAspect(){const[w,h]=formats[$("format").value];$("stage").style.aspectRatio=`${w}/${h}`;renderBlocks();}
function displaySize(px){const sw=$("stage").clientWidth||520;const[ew]=formats[$("format").value];return px*(sw/ew);}
function applyBg(){
  const el=$("backgroundLayer");
  if(bg.type==="solid"){el.style.background=bg.color;el.style.backgroundImage="none";}
  else if(bg.type==="gradient"){el.style.background=`linear-gradient(${bg.gradient.join(",")})`;}
  else if(bg.type==="image"&&bg.image){const size=bg.scale==="actual"?"auto":bg.scale;el.style.backgroundColor="#000";el.style.backgroundImage=`linear-gradient(rgba(0,0,0,${bg.darkness/100}),rgba(0,0,0,${bg.darkness/100})),url("${bg.image}")`;el.style.backgroundSize=`cover, ${size}`;el.style.backgroundRepeat="no-repeat,no-repeat";el.style.backgroundPosition=`center, ${bg.posX}% ${bg.posY}%`;}
}
function renderBlocks(){
  const layer=$("textLayer"), old=new Map([...layer.querySelectorAll(".textBlock")].map(e=>[Number(e.dataset.id),e]));
  for(const b of blocks){
    let el=old.get(b.id);
    if(!el){el=document.createElement("div");el.className="textBlock";el.dataset.id=b.id;el.contentEditable="true";el.spellcheck=true;layer.appendChild(el);wireBlock(el);}
    if(document.activeElement!==el)el.innerText=b.text;
    el.style.left=`${b.x}%`;el.style.top=`${b.y}%`;el.style.width=`${b.width}%`;el.style.fontFamily=b.font;el.style.fontSize=`${displaySize(b.size)}px`;el.style.color=b.color;el.style.textAlign=b.align;el.style.lineHeight=b.lineHeight;el.style.fontWeight=b.bold?"700":"400";el.style.fontStyle=b.italic?"italic":"normal";el.style.textShadow=b.shadow?"0 2px 4px rgba(0,0,0,.55)":"none";el.classList.toggle("selected",b.id===selectedId);old.delete(b.id);
  }
  old.forEach(e=>e.remove());updateControls();
}
function wireBlock(el){
  el.addEventListener("focus",()=>select(Number(el.dataset.id)));
  el.addEventListener("click",()=>select(Number(el.dataset.id)));
  el.addEventListener("input",()=>{const b=byId(Number(el.dataset.id));if(b)b.text=el.innerText;});
  el.addEventListener("pointerdown",e=>{const rect=el.getBoundingClientRect();const edge=e.offsetX<10||e.offsetX>rect.width-10||e.offsetY<8||e.offsetY>rect.height-8;if(edge||e.altKey||e.metaKey){e.preventDefault();select(Number(el.dataset.id));const b=byId(Number(el.dataset.id));dragState={type:"text",id:b.id,startX:e.clientX,startY:e.clientY,startBX:b.x,startBY:b.y};el.classList.add("dragging");}});
}
window.addEventListener("pointermove",e=>{if(!dragState)return;const r=$("stage").getBoundingClientRect();if(dragState.type==="text"){const b=byId(dragState.id);b.x=Math.max(5,Math.min(95,dragState.startBX+(e.clientX-dragState.startX)/r.width*100));b.y=Math.max(5,Math.min(95,dragState.startBY+(e.clientY-dragState.startY)/r.height*100));renderBlocks();}else if(bg.type==="image"){bg.posX=Math.max(0,Math.min(100,dragState.startBX-(e.clientX-dragState.startX)/r.width*100));bg.posY=Math.max(0,Math.min(100,dragState.startBY-(e.clientY-dragState.startY)/r.height*100));applyBg();}});
window.addEventListener("pointerup",()=>{document.querySelectorAll(".dragging").forEach(e=>e.classList.remove("dragging"));dragState=null;});
$("stage").addEventListener("pointerdown",e=>{if(e.target.closest(".textBlock"))return;if(bg.type==="image")dragState={type:"bg",startX:e.clientX,startY:e.clientY,startBX:bg.posX,startBY:bg.posY};else select(null);});

function select(id){selectedId=id;renderBlocks();const b=byId(id);$("selectionLabel").textContent=b?`Text ${blocks.indexOf(b)+1} selected`:"No text selected";}
function updateControls(){const b=byId(selectedId);$("noSelection").classList.toggle("hidden",!!b);$("textControls").classList.toggle("disabled",!b);if(!b)return;$("fontFamily").value=b.font;$("textColor").value=b.color;$("fontSize").value=b.size;$("fontSizeValue").textContent=`${b.size}px`;$("lineHeight").value=b.lineHeight;$("lineHeightValue").textContent=b.lineHeight;$("textWidth").value=b.width;$("widthValue").textContent=`${b.width}%`;document.querySelectorAll("[data-align]").forEach(x=>x.classList.toggle("active",x.dataset.align===b.align));$("boldBtn").classList.toggle("active",b.bold);$("italicBtn").classList.toggle("active",b.italic);$("shadowBtn").classList.toggle("active",b.shadow);}
function change(fn){const b=byId(selectedId);if(!b)return;fn(b);renderBlocks();}
function addText(text="New text"){const b=makeBlock(text);if(blocks.length)b.y=Math.min(85,42+blocks.length*10);blocks.push(b);selectedId=b.id;renderBlocks();setTimeout(()=>{const el=document.querySelector(`.textBlock[data-id="${b.id}"]`);if(el){el.focus();const r=document.createRange(),s=window.getSelection();r.selectNodeContents(el);s.removeAllRanges();s.addRange(r);}},0);}
function deleteText(){if(selectedId==null)return;blocks=blocks.filter(b=>b.id!==selectedId);selectedId=blocks.at(-1)?.id??null;renderBlocks();}
function insertEmoji(e){let b=byId(selectedId);if(!b){addText(e);return;}const el=document.querySelector(`.textBlock[data-id="${b.id}"]`);if(document.activeElement===el&&window.getSelection()?.rangeCount){document.execCommand("insertText",false,e);b.text=el.innerText;}else{b.text+=e;renderBlocks();}}

async function loadImage(src){return new Promise((res,rej)=>{const i=new Image();i.crossOrigin="anonymous";i.onload=()=>res(i);i.onerror=rej;i.src=src;});}
async function useImage(src){try{bg={...bg,type:"image",image:src,imageObj:await loadImage(src),posX:50,posY:50};$("uploadControls").classList.remove("hidden");applyBg();}catch{setStatus("Could not load this image.",false);}}
function tabTo(n){document.querySelectorAll(".tab").forEach(t=>t.classList.toggle("active",t.dataset.tab===n));document.querySelectorAll(".pane").forEach(p=>p.classList.toggle("active",p.id===`pane-${n}`));if(n==="featured")loadFeatured($("featuredSearch").value);}
function resetAll(){bg={type:"solid",color:"#ED213A",gradient:null,image:null,imageObj:null,scale:"contain",darkness:20,posX:50,posY:50};blocks=[];selectedId=null;nextId=1;$("postText").value="";$("format").value="landscape";$("downloadFormat").value="png";$("poweredBy").checked=false;$("poweredByText").style.display="none";$("imageUpload").value="";$("uploadControls").classList.add("hidden");stageAspect();applyBg();addText("What's on your mind?");setStatus("Reset.");}

function wrap(ctx,text,maxWidth){const lines=[];for(const para of text.split("\n")){if(!para){lines.push("");continue;}let line="";for(const word of para.split(/\s+/)){const test=line?`${line} ${word}`:word;if(ctx.measureText(test).width>maxWidth&&line){lines.push(line);line=word;}else line=test;}lines.push(line);}return lines;}
function makeGradient(ctx,w,h,g){const[d,...colors]=g;let gr;if(d==="to left")gr=ctx.createLinearGradient(w,0,0,0);else if(d==="to bottom")gr=ctx.createLinearGradient(0,0,0,h);else if(d==="to top")gr=ctx.createLinearGradient(0,h,0,0);else if(d==="45deg")gr=ctx.createLinearGradient(0,0,w,h);else if(d==="135deg")gr=ctx.createLinearGradient(0,h,w,0);else if(d==="225deg")gr=ctx.createLinearGradient(w,h,0,0);else if(d==="315deg")gr=ctx.createLinearGradient(w,0,0,h);else gr=ctx.createLinearGradient(0,0,w,0);colors.forEach((c,i)=>gr.addColorStop(colors.length===1?0:i/(colors.length-1),c));return gr;}
function drawImageBg(ctx,img,w,h){ctx.fillStyle="#000";ctx.fillRect(0,0,w,h);const ir=img.naturalWidth/img.naturalHeight,cr=w/h;let dw,dh;if(bg.scale==="actual"){dw=img.naturalWidth;dh=img.naturalHeight;}else if((bg.scale==="cover"&&ir>cr)||(bg.scale==="contain"&&ir<cr)){dh=h;dw=h*ir;}else{dw=w;dh=w/ir;}const x=(w-dw)/2-((bg.posX-50)/50)*(Math.max(0,dw-w)/2),y=(h-dh)/2-((bg.posY-50)/50)*(Math.max(0,dh-h)/2);ctx.drawImage(img,x,y,dw,dh);if(bg.darkness>0){ctx.fillStyle=`rgba(0,0,0,${bg.darkness/100})`;ctx.fillRect(0,0,w,h);}}
async function exportCanvas(){const c=$("exportCanvas"),ctx=c.getContext("2d"),[w,h]=formats[$("format").value];c.width=w;c.height=h;if(bg.type==="solid"){ctx.fillStyle=bg.color;ctx.fillRect(0,0,w,h);}else if(bg.type==="gradient"){ctx.fillStyle=makeGradient(ctx,w,h,bg.gradient);ctx.fillRect(0,0,w,h);}else if(bg.type==="image"&&bg.imageObj)drawImageBg(ctx,bg.imageObj,w,h);for(const b of blocks){if(!b.text.trim())continue;ctx.font=`${b.italic?"italic ":""}${b.bold?"700":"400"} ${b.size}px ${b.font}`;ctx.fillStyle=b.color;ctx.textBaseline="middle";ctx.textAlign=b.align;ctx.shadowColor=b.shadow?"rgba(0,0,0,.55)":"transparent";ctx.shadowBlur=b.shadow?8:0;ctx.shadowOffsetY=b.shadow?3:0;const mw=w*(b.width/100),lines=wrap(ctx,b.text,mw),lh=b.size*b.lineHeight,cx=w*(b.x/100),x=b.align==="left"?cx-mw/2:b.align==="right"?cx+mw/2:cx,y0=h*(b.y/100)-((lines.length-1)*lh)/2;lines.forEach((line,i)=>ctx.fillText(line,x,y0+i*lh,mw));}ctx.shadowColor="transparent";if($("poweredBy").checked){ctx.font="500 18px Arial";ctx.fillStyle="rgba(255,255,255,.72)";ctx.textAlign="right";ctx.fillText("Powered by MyPoint.Cards",w-20,h-20);}return c;}
async function insertIntoPost(){if(!blocks.some(b=>b.text.trim())&&bg.type!=="image"){setStatus("Add some text or an image first.",false);return;}try{const c=await exportCanvas(),[tab]=await chrome.tabs.query({active:true,currentWindow:true}),res=await chrome.tabs.sendMessage(tab.id,{type:"POSTCARD_INSERT",imageDataUrl:c.toDataURL("image/png"),postText:$("postText").value});if(res?.ok){setStatus("PostCard attached.");setTimeout(()=>window.close(),100);}else setStatus(res?.error||"Could not insert the card.",false);}catch{setStatus("Could not talk to this page. Reload it and try again.",false);}}
async function download(){const c=await exportCanvas(),fmt=$("downloadFormat").value,mime=fmt==="jpeg"?"image/jpeg":`image/${fmt}`,a=document.createElement("a");a.href=c.toDataURL(mime,.92);a.download=`postcard.${fmt==="jpeg"?"jpg":fmt}`;a.click();}
async function siteInfo(){try{const[tab]=await chrome.tabs.query({active:true,currentWindow:true}),res=await chrome.tabs.sendMessage(tab.id,{type:"POSTCARD_SITE_INFO"});$("siteBadge").textContent=res.supported?`✓ ${res.host}`:`Unsupported: ${res.host}`;$("insert").disabled=!res.supported;}catch{$("siteBadge").textContent="Open a supported social site";$("insert").disabled=true;}}
async function searchGiphy(){const q=$("giphySearch").value.trim();if(!q)return;$("giphyResults").className="imageGrid message";$("giphyResults").textContent="Searching…";try{const r=await fetch(`https://api.giphy.com/v1/gifs/search?api_key=${GIPHY_API_KEY}&q=${encodeURIComponent(q)}&limit=9&rating=g`),j=await r.json();$("giphyResults").className="imageGrid";$("giphyResults").innerHTML=(j.data||[]).map(g=>`<img class="imageChoice" data-image="${g.images.original.url}" src="${g.images.fixed_height_small.url}">`).join("")||"No results.";}catch{$("giphyResults").className="imageGrid message";$("giphyResults").textContent="Giphy search failed.";}}
async function loadFeatured(q=""){ $("featuredResults").className="imageGrid message";$("featuredResults").textContent="Loading…";try{const r=await fetch(FEATURED_ENDPOINT,{cache:"no-store"}),j=await r.json(),items=Object.values(j.featured||{}),s=q.trim().toLowerCase(),f=s?items.filter(x=>`${x.category||""} ${x.tags||""}`.toLowerCase().includes(s)):items;$("featuredResults").className="imageGrid";$("featuredResults").innerHTML=f.slice(0,36).map(x=>`<img class="imageChoice" data-image="${x["image-url"]}" src="${x["image-url"]}">`).join("")||"No matches.";}catch{$("featuredResults").className="imageGrid message";$("featuredResults").textContent="Featured images are unavailable right now.";}}

renderSwatches();
document.addEventListener("click",e=>{const tab=e.target.closest(".tab");if(tab)return tabTo(tab.dataset.tab);const s=e.target.closest("[data-solid]");if(s){bg={...bg,type:"solid",color:s.dataset.solid,image:null,imageObj:null};$("bgColor").value=s.dataset.solid;document.querySelectorAll(".swatch").forEach(x=>x.classList.remove("active"));s.classList.add("active");applyBg();return;}const g=e.target.closest("[data-gradient]");if(g){bg={...bg,type:"gradient",gradient:JSON.parse(g.dataset.gradient),image:null,imageObj:null};document.querySelectorAll(".swatch").forEach(x=>x.classList.remove("active"));g.classList.add("active");applyBg();return;}const em=e.target.closest("[data-emoji]");if(em)return insertEmoji(em.dataset.emoji);const im=e.target.closest("[data-image]");if(im)return useImage(im.dataset.image);const sc=e.target.closest("[data-scale]");if(sc){document.querySelectorAll("[data-scale]").forEach(x=>x.classList.remove("active"));sc.classList.add("active");bg.scale=sc.dataset.scale;applyBg();return;}const al=e.target.closest("[data-align]");if(al){change(b=>b.align=al.dataset.align);return;}});
$("addText").onclick=()=>addText("New text");$("deleteText").onclick=deleteText;
$("fontFamily").onchange=()=>change(b=>b.font=$("fontFamily").value);$("textColor").oninput=()=>change(b=>b.color=$("textColor").value);$("fontSize").oninput=()=>change(b=>b.size=Number($("fontSize").value));$("lineHeight").oninput=()=>change(b=>b.lineHeight=Number($("lineHeight").value));$("textWidth").oninput=()=>change(b=>b.width=Number($("textWidth").value));$("boldBtn").onclick=()=>change(b=>b.bold=!b.bold);$("italicBtn").onclick=()=>change(b=>b.italic=!b.italic);$("shadowBtn").onclick=()=>change(b=>b.shadow=!b.shadow);
$("poweredBy").onchange=()=>{$("poweredByText").style.display=$("poweredBy").checked?"block":"none";};$("format").onchange=stageAspect;
$("bgColor").oninput=()=>{bg={...bg,type:"solid",color:$("bgColor").value,image:null,imageObj:null};document.querySelectorAll(".swatch").forEach(x=>x.classList.remove("active"));applyBg();};
$("applyGradient").onclick=()=>{bg={...bg,type:"gradient",gradient:[$("gradientDirection").value,$("gradientColor1").value,$("gradientColor2").value],image:null,imageObj:null};document.querySelectorAll(".swatch").forEach(x=>x.classList.remove("active"));applyBg();};
$("imageUpload").onchange=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=async()=>{$("uploadPreview").src=r.result;$("uploadControls").classList.remove("hidden");await useImage(r.result);};r.readAsDataURL(f);};
$("removeUpload").onclick=()=>{bg={...bg,type:"solid",color:$("bgColor").value,image:null,imageObj:null};$("uploadControls").classList.add("hidden");$("imageUpload").value="";applyBg();};
$("darkness").oninput=()=>{bg.darkness=Number($("darkness").value);$("darknessValue").textContent=`${bg.darkness}%`;applyBg();};
$("giphyBtn").onclick=searchGiphy;$("giphySearch").onkeydown=e=>{if(e.key==="Enter")searchGiphy();};$("featuredBtn").onclick=()=>loadFeatured($("featuredSearch").value);$("featuredSearch").onkeydown=e=>{if(e.key==="Enter")loadFeatured($("featuredSearch").value);};
$("insert").onclick=insertIntoPost;$("download").onclick=download;$("reset").onclick=resetAll;
(async function(){stageAspect();applyBg();siteInfo();loadFeatured();const s=await chrome.storage.local.get(["postcardSelectedText","postcardSelectedAt"]);if(s.postcardSelectedText&&Date.now()-(s.postcardSelectedAt||0)<600000){addText(s.postcardSelectedText);await chrome.storage.local.remove(["postcardSelectedText","postcardSelectedAt"]);}else addText("What's on your mind?");})();
